services:
  api:
    image: ghcr.io/zhumabekovalim/nesta:latest
    restart: unless-stopped
    env_file:
      - /srv/apps/nesta-server/.env
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - /srv/apps/nesta-server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
